### ISSUE TITLE
Schedule fixes task list

### ISSUE THREAD

**Issue by Demarsch** [Demarsch/ChildCare#127]
- [x] Async loading of data sources for ContentViewModel
- [x] Set min height for room headers so when no rooms are presented it doesn't change size
- [x] Set min width for mode change button so it doesn't get wider
- [x] Use failure mediator instead of error windows
- [x] Use interaction triggers instead of dialog windows
- [x] Move 'Отменить перенос' button to ribbon
- [x] Inject delegate factories for creating dialog view models
- [x] Async loading of data source for ScheduleAssignmentUpdateViewModel
- [x] Add button to clear all filters
- [x] Make white background
- [x] Set room and record type to unselected instead of null
