### ISSUE TITLE
Relatives task list

### ISSUE THREAD

**Issue by Demarsch** [Demarsch/ChildCare#130]
- [x] Cancel changes doesn't work
- [x] Gallery doesn't show relatives in horizontal manner
- [x] After saving relatives change tracker doesn't go into initial state
- [x] No more than one representative may exist at any time
- [x] Wrong relationship direction is saved for new person
- [x] Filter relationship by patient gender
- [x] Make view in relative mode look distinct
